module.exports = {
    fíor: true,
    bréagach: false,
    nó: "or",
    agus: "and",
    tada: "null",
    faic: "null",
    nua: "new",
    fill: "return",
    do: "for",
    "de na": "of",
    Botún: "Error",
    "lean ar aighaidh": "continue",
    bris: "break",
    consól: "console",
    eoalas: "info",
    dífadhbtaigh: "debug",
    fólaireamh: "warn",
    earráid: "error",
    loga: "log",
};
